services:
  - type: web
    name: edunotes-api
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt && python scripts/setup_kb.py --init && python scripts/seed_data.py --sample
    startCommand: uvicorn src.api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: groq

  - type: web
    name: edunotes-ui
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run ui/streamlit_app.py --server.port $PORT --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: API_BASE_URL
        value: http://edunotes-api-s9xc:10000/api/v1
